# Site settings
title: Jake Plus
email: Jake@JakePlus.com
description: Indy Artist, Producer, & Engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://JakePlus.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty
